import Card from "@/components/Card";
import ProfileUpdateInfoForm from "@/components/ProfileUpdateInfoForm";
import ReturnBackIcon from "@/components/ReturnBackIcon";
import UserAvatar from "@/components/UserAvatar";
import { mockDataProfile } from "@/lib/data";
import { ProfileType } from "@/lib/type";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "PakiSlot | Profile Page",
  description: "Generated by create next app",
};

async function ProfileCard() {
  const getUserProfile = async () => {
    const profile = mockDataProfile;
    if (!profile) {
      throw new Error(
        "Cannot get the user's profile.\nPlease check your internet connection."
      );
    }
    return profile;
  };

  const profile: ProfileType | null = await getUserProfile(); // fetch api

  return (
    <>
      <Card className="w-full h-full p-5 rounded-none shadow-xl">
        <ReturnBackIcon />
        <div className="w-full h-full items-start flex flex-col gap-10 px-1 md:px-6">
          <div className="justify-center items-end gap-6 flex">
            <UserAvatar />
            <span className="text-neutral-900 text-lg font-semibold sm:text-2xl">
              {profile.name}
            </span>
          </div>
          <ProfileUpdateInfoForm profile={profile} />
        </div>
      </Card>
    </>
  );
}

export default function Profile() {
  return (
    <div className="w-full h-[100dvh] px-4 pt-20 pb-6 overflow-hidden relative">
      <div className="absolute inset-0 z-0 w-full h-52 bg-neutral-800 p-4 px-6">
        <span className="text-white font-semibold uppercase text-xl">
          Your Profile
        </span>
      </div>
      <div className="w-full relative mx-auto h-full md:w-4/5 xl:w-3/5">
        <ProfileCard />
      </div>
    </div>
  );
}
